#!/bin/bash
lr=${1:-0.03}
wd=${2:-0.1}
damping=${3:-0.0}
opnorm_target=${4:-null}
per_layer_damping=${5:-true}
ema_beta=${6:-0.99}
output_cov_mode=${7:-null}
abs_damping=${8:-null}
trace_damping=${9:-null}
precond_only_opnorm=${10:-false}
seed=${11:-42}

ALLOW_DIRTY=1 python -u run_hydra.py \
    model=gpt-tiny \
    training=fineweb1B_tiny \
    data=fineweb1B \
    optimizer=dap-opnorm \
    logging=default \
    "optimizer.optimizer_params.lr=${lr}" \
    "optimizer.optimizer_params.weight_decay=${wd}" \
    "optimizer.optimizer_params.damping=${damping}" \
    "optimizer.optimizer_params.opnorm_target=${opnorm_target}" \
    "optimizer.optimizer_params.per_layer_damping=${per_layer_damping}" \
    "optimizer.optimizer_params.ema_beta=${ema_beta}" \
    "optimizer.optimizer_params.output_cov_mode=${output_cov_mode}" \
    "optimizer.optimizer_params.abs_damping=${abs_damping}" \
    "optimizer.optimizer_params.trace_damping=${trace_damping}" \
    "optimizer.optimizer_params.precond_only_opnorm=${precond_only_opnorm}" \
    "seed=${seed}"
