# config.yaml
optimizer_params:
  - name: sign-gd
    lr: [0.00003, 0.0001, 0.0003, 0.001, 0.003, 0.01]
    weight_decay: 0.0
    momentum: 0.0
    nesterov: False
    lr_schedule: constant

  - name: sign-gd-nonlmo
    lr: [3.0e-9, 1.0e-8, 3.0e-8, 1.0e-7, 3.0e-7, 1.0e-6, 3.0e-6, 1.0e-5, 3.0e-5, 1.0e-4]
    weight_decay: 0.0
    momentum: 0.0
    nesterov: False
    lr_schedule: constant

  - name: adamw
    lr: [0.00003, 0.0001, 0.0003, 0.001, 0.003, 0.01]
    weight_decay: 0.0
    betas: [0.0, 0.999]
    lr_schedule: constant

training_params:
  tokens_processed: 524288 # 2^19
  val_tokens_processed: 8388608 #2^23
  batch_size: 64
  num_epochs: 1
  context_length: 1024
  gradnorm: 1.0
  tensorcore_precision: high   #Can be highest, high, or medium
  autocast: True
  mixed_precision: bfloat16
  compile: True

logging_params:
  val_tokens_processed: 8388608 #2^23
  log_step: 256
  val_step: 256
  save_ckpt_step: 512
  load_ckpt_step: 0
  keep_last: 2
  ckpt_dir: "" #/mnt/ceph/users/cmodi/gptopt/

gpt_model:
  n_embd: 768    
  n_layer: 12   
  n_head: 12    
  vocab_size: 50257
  flash_attention: True

dataset:
  name: "fineweb1B"
