# config.yaml
optimizer_params:
  - name: adamw
    lr: [0.0001, 0.0005, 0.001]
    weight_decay: 0.1
    lr_schedule: warm-up-cosine
    warm_up_fraction: 0.1

  - name: momo-adam
    lr: [0.0001, 0.0005, 0.001]
    weight_decay: 0.1
    lb: 2.5
    lr_schedule: warm-up-cosine
    warm_up_fraction: 0.1

  - name: muon
    lr: [0.0001, 0.0005, 0.001]
    weight_decay: 0.1
    lr_schedule: warm-up-cosine
    warm_up_fraction: 0.1

training_params:
  tokens_processed: 262144 # 2^18  # 524288 # 2^19
  val_tokens_processed: 8388608 #2^23
  batch_size: 32
  num_epochs: 1
  context_length: 1024
  gradnorm: 1.0
  tensorcore_precision: high   #Can be highest, high, or medium
  autocast: True
  mixed_precision: bfloat16
  compile: True

logging_params:
  val_tokens_processed: 8388608 #2^23
  log_step: 50
  val_step: 50
  save_ckpt_step: 100
  load_ckpt_step: 0
  keep_last: 2
  ckpt_dir: "" #/mnt/ceph/users/cmodi/gptopt/

gpt_model:
  n_embd: 768    
  n_layer: 12   
  n_head: 12    
  vocab_size: 50257
  flash_attention: True

dataset:
  name: "finewebmini"