# config.yaml
optimizer_params:
  - name: dap-sgd
    lr: [0.00003, 0.0001, 0.0003, 0.001, 0.003, 0.01, 0.03]
    weight_decay: 0
    lr_schedule: constant
    ema_beta: 0
    momentum: 0
    wd: 0
    sgd_update: True
    scalar: False

  - name: dap-scalar
    lr: [0.00003, 0.0001, 0.0003, 0.001, 0.003, 0.01, 0.03]
    weight_decay: 0
    lr_schedule: constant
    ema_beta: 0
    momentum: 0
    wd: 0
    sgd_update: False
    scalar: True

  - name: dap
    lr: [0.00003, 0.0001, 0.0003, 0.001, 0.003, 0.01, 0.03]
    weight_decay: 0
    lr_schedule: constant
    ema_beta: 0
    momentum: 0
    wd: 0
    sgd_update: False
    scalar: False

training_params:
  tokens_processed: 2048 # 2^11  # 524288 # 2^19
  val_tokens_processed: 8388608 #2^23
  batch_size: 2
  num_epochs: 1
  context_length: 512
  gradnorm: 1.0
  tensorcore_precision: high   #Can be highest, high, or medium
  autocast: True
  mixed_precision: bfloat16
  compile: False

logging_params:
  val_tokens_processed: 2048 #2^23
  log_step: 50
  val_step: 50
  save_ckpt_step: 500
  load_ckpt_step: 0
  keep_last: 2
  ckpt_dir: "" #/mnt/ceph/users/cmodi/gptopt/
  

gpt_model:
  n_embd: 768    
  n_layer: 12   
  n_head: 12    
  vocab_size: 50257
  flash_attention: True

dataset:
  name: "tiny_shakespeare"  
