defaults:
  - gpt_model: gpt-small
  - _self_

optimizer_params:
  name: adamw
  lr: 0.001
  weight_decay: 0.1
  lr_schedule: constant-linear
  warm_up_fraction: 0.4
  ns_steps: 5  # this isn't used for adamw but needed for muon optimizers

logging_params:
  val_tokens_processed: 16384  # 2^14
  log_step: 50
  val_step: 50
  save_ckpt_step: 500
  load_ckpt_step: 0
  keep_last: 2
  ckpt_dir: ""  # "outputs/checkpoints"
  results_dir: "outputs/hydra-results/my_experiment"
  # wandb:
  #   project: "polar-express"
